language: node
node_js:
    - "6"

install:
    npm install webdriverio



before_script:
    curl -O http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.48.2.jar
    java -jar selenium-server-standalone-2.48.2.jar
    export DISPLAY=:0.0


script:
    node test.js