language: node
node_js:
    - "6"

install:
    npm install webdriverio


before_script:
    java -jar selenium-server-standalone-2.53.0.jar &> selenium_server.log &
    export DISPLAY=:0.0


script:
    node test.js