language: node
node_js:
    - "6"

install:
    npm install webdriverio


before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - java -jar selenium-server-standalone-2.53.0.jar &> selenium_server.log &
    - export DISPLAY=:0.0


script:
    ps aux | grep "sele"
    node test.js