language: node
node_js:
    - "6"

install:
    npm install webdriverio


before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - nohup java -jar selenium-server-standalone-2.53.0.jar > selenium_server.log &
    - until nc -z localhost 4444; do echo Waiting for Selenium; sleep 1; done

script:
    - ps aux | grep "sele"
    - node test.js